[package]
name = "elfmt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.11", features = ["derive"] }
elf = "0.7.4"
iced-x86 = "1.20.0"
rustc-hex = "2.1.0"
